# Generated by Django 5.2.7 on 2025-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Scadenza'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Attivo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
