# Generated by Django 5.2.7 on 2026-06-15 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberdocument_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Settore')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Settore',
                'verbose_name_plural': 'Settori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportsBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ente')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Sigla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Ente sportivo',
                'verbose_name_plural': 'Enti sportivi',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, max_length=120, verbose_name='Luogo di nascita'),
        ),
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, help_text='Formato es. BS/23/00202', max_length=30, null=True, unique=True, verbose_name='Numero tessera'),
        ),
        migrations.AddField(
            model_name='member',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Codice fiscale'),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to=settings.AUTH_USER_MODEL, verbose_name='Genitore / tutore'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_dismissed',
            field=models.BooleanField(default=False, verbose_name='Dimesso / Cessato'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_home',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono casa'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='member',
            name='province',
            field=models.CharField(blank=True, max_length=2, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data registrazione'),
        ),
        migrations.AddField(
            model_name='member',
            name='residence_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Comune di residenza'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Amministratore'), ('STAFF', 'Segreteria'), ('INSTRUCTOR', 'Istruttore'), ('MEMBER', 'Socio')], default='MEMBER', max_length=20, verbose_name='Ruolo'),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cellulare'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Cognome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Account collegato')),
                ('sectors', models.ManyToManyField(blank=True, related_name='instructors', to='members.sector', verbose_name='Settori')),
            ],
            options={
                'verbose_name': 'Insegnante tecnico',
                'verbose_name_plural': 'Insegnanti tecnici',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.instructor', verbose_name='Insegnante tecnico'),
        ),
        migrations.AddField(
            model_name='member',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.sector', verbose_name='Settore'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('MONTHLY', 'Mensile'), ('QUARTERLY', 'Trimestrale'), ('FOURMONTH', 'Quadrimestrale'), ('SEMESTRAL', 'Semestrale'), ('ANNUAL', 'Annuale')], max_length=20, verbose_name='Tipologia abbonamento')),
                ('start_date', models.DateField(verbose_name='Data inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data fine')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='members.sector', verbose_name='Settore')),
            ],
            options={
                'verbose_name': 'Abbonamento',
                'verbose_name_plural': 'Abbonamenti',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('ENROLLMENT', 'Iscrizione'), ('MONTHLY', 'Mensile'), ('QUARTERLY', 'Trimestrale'), ('FOURMONTH', 'Quadrimestrale')], max_length=20, verbose_name='Tipo')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data pagamento')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Scadenza')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Prossima scadenza')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quota €')),
                ('enrollment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Iscrizione €')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sconto €')),
                ('payment_mode', models.CharField(blank=True, choices=[('C', 'Contanti'), ('B', 'Bonifico / POS')], max_length=2, verbose_name='Modalità')),
                ('fee_code', models.CharField(blank=True, max_length=5, verbose_name='Tariffa')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Pagato')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.subscription', verbose_name='Abbonamento collegato')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-due_date', '-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_card', models.CharField(blank=True, max_length=50, verbose_name='Tessera federale')),
                ('federal_card_expiry', models.DateField(blank=True, null=True, verbose_name='Scadenza tessera')),
                ('federal_license', models.CharField(blank=True, max_length=50, verbose_name='Licenza federale')),
                ('affiliation_year', models.CharField(blank=True, help_text='Es. 2023/2026', max_length=20, verbose_name='Anno affiliazione')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliations', to='members.sportsbody', verbose_name='Ente')),
            ],
            options={
                'verbose_name': 'Affiliazione',
                'verbose_name_plural': 'Affiliazioni',
                'ordering': ['body__name'],
                'unique_together': {('member', 'body')},
            },
        ),
    ]
