# Generated by Django 5.2.7 on 2026-06-15 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_sector_sportsbody_member_birth_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome pacchetto')),
                ('package_type', models.CharField(choices=[('MONTHLY', 'Mensile'), ('QUARTERLY', 'Trimestrale'), ('FOURMONTH', 'Quadrimestrale'), ('SEMESTRAL', 'Semestrale'), ('ANNUAL', 'Annuale')], max_length=20, verbose_name='Tipo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prezzo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='members.sector', verbose_name='Settore')),
            ],
            options={
                'verbose_name': 'Pacchetto',
                'verbose_name_plural': 'Listino pacchetti',
                'ordering': ['sector__name', 'name'],
            },
        ),
    ]
